### ISSUE TITLE
A potential pitfall

### ISSUE THREAD

**Issue by zhongyujun222** [rwhitt2049/trouve#23]
For an array of time series data, if the data suddenly got lost without recording the actual shut down value, and the beginning of the next session is also not stored, trouve would see it as one event as opposed to two separate events. I'm talking about if the data is missing for a long time (hours) instead of seconds because if it only lasts for seconds then it can be fixed by using the transformation: debounce.

**Comment by rwhitt2049** [comment]
I'm not sure I follow @zhongyujun222 . Do you have any examples that you can show me?
